sp:
  user-service:
    users: "[{\"id\":77, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":123321, \"username\":\"aaa\",\"password\":\"111\"}]"

spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.73.129
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka  

management:
  endpoints:
    web:
      exposure:
        include: refresh
